.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. ruxcoin_qt test_ruxcoin_qt
clean: FORCE
	$(MAKE) -C .. ruxcoin_qt_clean test_ruxcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_ruxcoin_qt_check
ruxcoin-qt ruxcoin-qt.exe: FORCE
	 $(MAKE) -C .. ruxcoin_qt
